apiVersion: v2
name: zero-day-framework
description: Kubernetes Zero-Day Mitigation Framework
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: "Your Name"
    email: "your.email@example.com"
dependencies:
  - name: prometheus
    version: 15.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
