apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-quarantine-sa
  namespace: security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-quarantine-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch", "delete", "patch"]
- apiGroups: [""]
  resources: ["nodes/status"]
  verbs: ["patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-quarantine-binding
subjects:
- kind: ServiceAccount
  name: pod-quarantine-sa
  namespace: security
roleRef:
  kind: ClusterRole
  name: pod-quarantine-role
  apiGroup: rbac.authorization.k8s.io
