apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "zero-day-framework.fullname" . }}-monitor
  labels:
    {{- include "zero-day-framework.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zero-day-framework.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "zero-day-framework.fullname" . }}-rules
  labels:
    {{- include "zero-day-framework.labels" . | nindent 4 }}
spec:
  groups:
  - name: zero-day.rules
    rules:
    - alert: HighQuarantineRate
      expr: rate(quarantine_actions_total[5m]) > 5
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High rate of pod quarantines
        description: More than 5 pods quarantined in the last 5 minutes
    
    - alert: QuarantineFailure
      expr: rate(quarantine_failures_total[5m]) > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Quarantine action failed
        description: Pod quarantine action failed

    - alert: UnusualPodTermination
      expr: kube_pod_container_status_terminated_reason{reason!~"Completed|Error"} > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Unusual pod termination pattern detected
        description: Pod terminated for unexpected reasons
