apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "zero-day-framework.fullname" . }}-network-policy
  labels:
    {{- include "zero-day-framework.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      quarantine-status: active
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "zero-day-framework.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 9090
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: 443
      endPort: 443
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
    ports:
    - protocol: TCP
      port: 9090
