apiVersion: aquasecurity.github.io/v1alpha1
kind: VulnerabilityPolicy
metadata:
  name: zero-day-vuln-policy
spec:
  severity: High,Critical
  packageName: "*"
  imagePattern: "*"
  namespacePattern: "*"
  reportTtl: 24h
  allowlist:
    expiration: 2025-12-31T23:59:59Z
    vulnerabilities: []
---
apiVersion: aquasecurity.github.io/v1alpha1
kind: ConfigAuditPolicy
metadata:
  name: zero-day-config-audit
spec:
  rules:
    - name: privileged-containers
      match:
        kinds: ["Pod", "Deployment", "StatefulSet", "DaemonSet"]
      checkOn: CREATE,UPDATE
      ruleSetting:
        minimumSeverity: HIGH
      deny:
        conditions:
          all:
            - key: spec.containers[*].securityContext.privileged
              operator: Equals
              value: true
    - name: root-containers
      match:
        kinds: ["Pod", "Deployment", "StatefulSet", "DaemonSet"]
      checkOn: CREATE,UPDATE
      ruleSetting:
        minimumSeverity: HIGH
      deny:
        conditions:
          all:
            - key: spec.containers[*].securityContext.runAsUser
              operator: Equals
              value: 0
    - name: unsafe-sysctls
      match:
        kinds: ["Pod"]
      checkOn: CREATE,UPDATE
      ruleSetting:
        minimumSeverity: HIGH
      deny:
        conditions:
          all:
            - key: spec.securityContext.sysctls[*].name
              operator: Contains
              value: "net.ipv4.route.min_pmtu"
